### ISSUE TITLE
Weekly reset of database to remove un-synced keys

### ISSUE THREAD

**Issue by Zaltany** [Mgp1502/wowkeys#2]
Implementation of a database reset to remove keys, that because the weekly reset no longer would be current.

**Comment by Zaltany** [comment]
Issues of un-synced keys also arises when character namechanges happen,
![image](https://user-images.githubusercontent.com/63681174/79623205-31555f00-811b-11ea-84f2-bf01d5feb8f7.png)

**Comment by Mgp1502** [comment]
The reset of the keys table is now done on the database side of things (should happen at resetday at 8:00), and there is support in the HootBot to clear a name from DB as a non-admin user.
